# Weave Scorer Server Configuration
# This file contains default settings for the Weave scorer server

# Server settings
host: "0.0.0.0"
port: 8001

# Performance settings
max_batch_size: 32
batch_timeout: 0.1  # seconds
num_workers: 4

# Caching settings
enable_caching: true
cache_size: 1000

# Logging
log_level: "INFO"

# Available scorers (comment out to disable)
available_scorers:
  - "bias"
  - "toxicity" 
  - "hallucination"
  - "context_relevance"
  - "coherence"
  - "fluency"
  - "trust"
  - "pii"

# Scorer-specific settings (optional)
scorer_settings:
  pii:
    default_language: "en"
    default_entities: ["PERSON", "EMAIL_ADDRESS", "PHONE_NUMBER"]
  
  trust:
    # Trust scorer combines multiple other scorers
    critical_threshold: 0.8
    advisory_threshold: 0.6